---
- hosts: localhost

  tasks:
#  - include_vars: users.yml

  - name: install openssh-server
    yum:
       name: openssh-server
       state: latest

  - name: ensure openssh-server is running
    service:
       name: sshd
       state: stopped

  - name: allow root SSH access
    lineinfile: dest=/etc/ssh/sshd_config
       regexp="^#PermitRootLogin"
       line="PermitRootLogin yes"
       state=present
    notify:
       - restart sshd

  - name: enable sshd service
    service:
       name: sshd
       enabled: true

  - name: Add officenames
    user:
       name: "{{ item.username }}"
       shell: /sbin/nologin
       generate_ssh_key: yes
       ssh_key_bits: 4096
       ssh_key_file: .ssh/id_rsa
#    with_items: '{{ users }}'
    with_items:
       - { username: jon }
       - { username: mark }
       - { username: tom }

  handlers:
     - name: restart sshd
       service:
          name: sshd
          state: restarted
